### ISSUE TITLE
Tentative timeline for code and model release

### ISSUE THREAD

**Issue by Mrs-Hudson** [henryzhao5852/AutoEM#1]
Hi

Will the code and models be added here?

**Comment by Raidus** [comment]
Would be also very interested in the model implementation.

**Comment by shgoren** [comment]
Hi, I really hope you are planning on uploading the pretrained models as you said as there is nothing like it freely available as far as I know

Thanks!

**Comment by argenisleon** [comment]
Eager to test this. Any estimate when the pre-trained model will be released?

**Comment by ejohb** [comment]
Also interested!

**Comment by konferzehl** [comment]
Interested as well!

**Comment by nishadi** [comment]
Hi, Any update on the models?

**Comment by Gaurav-GVV** [comment]
Any update on when this is planned to be released

**Comment by fjsj** [comment]
Any updates?

**Comment by shubhpawar** [comment]
Hi, any update on this?
