### ISSUE TITLE
Syntax error in matching/model/rnn_encoder.py.

### ISSUE THREAD

**Issue by Peter-Varga08** [henryzhao5852/AutoEM#2]
Dear authors,

There are several Syntax Errors stemming from wrong variable names within the `forward` function of the Entity Maching model, inside 
`matching/model/rnn_encoder.py.`  I am not sure how to fix it, because due to the naming conventions it is non-trivial.

It is only 24 lines, so I am sending the code snippet below that contains the errors:

```
def forward(self, alias1, alias1_word_mask, alias1_char_mask, alias2, alias2_word_mask, is_sample=False):
device = torch.device("cuda")
batch_size, word_max_len1, char_max_len1 = alias1.size(0)
alias = alias.view(batch_size * word_max_len, char_max_len)

alias_rep = self.embeddings(alias)

alias_char_len = alias_char_mask.view(batch_size * word_max_len, char_max_len).data.eq(0).long().sum(1).cpu().numpy().tolist()
alias_char_idx = [i for i in range(len(alias_char_len)) if alias_char_len[i] > 0]
alias_char_mask = alias_char_mask.view(batch_size * word_max_len, char_max_len)[alias_char_idx]
alias_char_len = [i for i in alias_char_len if i > 0]
alias_rep = alias_rep[alias_char_idx]
alias_rep = self.char_encoder(alias_rep, alias_char_len)

alias_rep = self.char_self_attn(alias_rep, alias_char_mask)
del alias_char_mask

alias_word_rep = torch.FloatTensor(batch_size * word_max_len, 2 * self.args.hidden_size).zero_().to(device)
alias_word_rep[alias_char_idx] = alias_rep
#del alias_rep

alias_word_rep = alias_word_rep.view(batch_size, word_max_len, -1)
alias_word_len = alias_word_mask.data.cpu().eq(0).long().sum(1).cpu().numpy().tolist()

return self.word_encoder(alias_word_rep, alias_word_len, is_sample)
```

As you can see, `alias1_word_mask`, `alias1_char_mask`, `alias2`, `alias2_word_mask` are all in the arguments of the function, but they are in fact never used (properly) which leaves the subsequent expressions with undefined variables.

**Comment by henryzhao5852** [comment]
Thanks for your interest, sorry about the confusion. Could you help check which code fragment uses this module (Hybrid_Alias_Rep), as I could not find it. If none of the code used this module, it might be fine to just ignore this function.

**Comment by Peter-Varga08** [comment]
You are right. It is not used, but since it seems like a simplified version of `Hybrid_Alias_Sim`,I thought it was perhaps for the sake of calculating feature representations of words for analytical purposes (which might be useful to know before the attention gets applied).
Is it completely redundant then, in case I would only like to pass the data through the pipeline described in the paper?

**Comment by henryzhao5852** [comment]
Yes, I think so, feel free to ask questions if you have more.
